
  - name: Create directory for Docker proxy configure file
    file:
      path: '/etc/systemd/system/docker.service.d'
      state: directory

  - name: Create Docker proxy configure file
    file:
      path: '/etc/systemd/system/docker.service.d/http-proxy.conf'
      state: touch

  - name: Modify Docker proxy
    blockinfile:
      path: '/etc/systemd/system/docker.service.d/http-proxy.conf'
      block: '[Service]

              Environment=
              "HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/"

              "HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/"

              "http_proxy=http://wwwproxy.unimelb.edu.au:8000/"

              "https_proxy=http://wwwproxy.unimelb.edu.au:8000/"

              "no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"
              '
      state: present

  - name: reload docker
    systemd:
      name: docker
      daemon_reload: yes
      state: restarted
