  - hosts: dbserver
    become: yes
    vars_files:
      - host_vars/cloud-common.yaml
    gather_facts: true

    roles:
      - role: cloud-install-docker-dependencies
      - role: cloud-install-docker
      - role: cloud-modify-docker-proxy
      - role: cloud-run-couchdb
      - role: cloud-setup-cluster
