  # set fact sg_names
  - name: Remove a list of security groups
    set_fact:
      sg_names: '{{ sg_names|default([]) + [ item.name ] }}'
    loop: '{{ security_groups }}'

  # remove instances
  - name: Remove an instance
    os_server:
      name: '{{ item.name }}'
      image: '{{ instance_image }}'
      key_name: '{{ instance_key_name }}'
      flavor: '{{ item.flavor }}'
      availability_zone: '{{ availability_zone }}'
      security_groups: '{{ sg_names }}'
      volumes: '{{ item.volumes }}'
      auto_floating_ip: yes
      wait: yes
      timeout: 600
      state: absent
    loop: '{{ instances }}'
    register: os_instance


  # remove volumn
  - name: Remove volume on NeCTAR
    os_volume:
      display_name: '{{ item.vol_name }}'
      size: '{{ item.vol_size }}'
      availability_zone: '{{ availability_zone }}'
      wait: yes
      timeout: 600
      state: absent
    loop: '{{ volumes }}'
    register: os_vol

  # remove security rules
  - name: Remove security group rules
    os_security_group_rule:
      security_group: '{{ item.name }}'
      protocol: '{{ item.protocol }}'
      port_range_min: '{{ item.port_range_min }}'
      port_range_max: '{{ item.port_range_max }}'
      remote_ip_prefix: '{{ item.remote_ip_prefix }}'
      state: absent
    loop: '{{ security_groups }}'

  # remove security group
  - name: Remove a security group
    os_security_group:
      name: '{{ item.name }}'
      description: '{{ item.description }}'
      state: absent
    loop: '{{ security_groups }}'

  

