  - name: Install flask packages
    become: yes
    pip:
      name: ['Flask', 'couchdb']

#  - name: Git clone repository
#    git:
#      repo: "{{project_repo}}"
#      dest: "{{project_path}}"
#      accept_hostkey: yes
#      force: yes
#
#  - name: Offer permission to directory
#    become: yes
#    file:
#      path: "{{project_path}}"
#      mode: '1777'
#      state: directory
#      recurse: yes

  - name: Run the webserver
    shell: "python3 {{project_path}}/web_server/src/main.py"