#  - name: Install server dependencies
#    become: yes
#    pip:
#      name: ['Flask', 'couchdb']
#
#  - name: Git clone repository
#    git:
#      repo: "{{project_repo}}"
#      dest: "{{project_path}}"
#      accept_hostkey: yes
#      force: yes
#
#  - name: Offer permission to directory
#    become: yes
#    file:
#      path: "{{project_path}}"
#      mode: '1777'
#      state: directory
#      recurse: yes

  - name: Shut down the server
    uri:
      url: http://{{ ansible_default_ipv4.address }}:5000/shutdown
      timeout: 10
    ignore_errors: yes

  - name: Run the webserver
    become: yes
    shell: "python3 {{project_path}}/web_server/src/main.py"
    async: 47476648
    poll: 0
